### ISSUE TITLE
A bug in issue message. It's assigning label as gssoc'21. 

### ISSUE THREAD

**Issue by saimanoharhm** [DSC-SIST/Discord-Bot#16]
![image](https://user-images.githubusercontent.com/72253236/112195432-f6fc1800-8c2f-11eb-95cb-a5d41a4bf1ce.png)

**Comment by Sriram-bb63** [comment]
I would like to solve this issue

**Comment by KamalDGRT** [comment]
Good work @Sriram-bb63 :tada:
