### ISSUE TITLE
[Feature] Github updates

### ISSUE THREAD

**Issue by saimanoharhm** [DSC-SIST/Discord-Bot#28]
## Feature :rocket: 
Github Updates

### Objective :pushpin:

Lets say  we have a channel with the name github-updates.
This will be the purpose of that channel:

- if someone created an issue or a PR, it will send a message to the github-updates channel.
- It is similar to how the Discord Bot welcomes the new user when he joins the server.

### Features to be added / modified :ballot_box_with_check:

-   Get a discord message if someone has created an issue
-   Get a discord message if someone has created a pr

**Comment by KamalDGRT** [comment]
Since it is working now, I am closing the issue!
