### ISSUE TITLE
[Feature] Word of the day

### ISSUE THREAD

**Issue by saimanoharhm** [DSC-SIST/Discord-Bot#40]
## Feature :rocket:
Word of the day with its meaning: -word  (Mugunth)

### Objective :pushpin:
Let's say if someone has given a "-word" command 
- It will get the word of the day. 

### Features to be added / modified :ballot_box_with_check:

-   It gets the word of the day.

**Comment by KamalDGRT** [comment]
Closing the issue as the feature is reviewed and merged~
