### ISSUE TITLE
[Feature] Meaning of a word

### ISSUE THREAD

**Issue by saimanoharhm** [DSC-SIST/Discord-Bot#41]
## Feature :rocket:
Meaning of a word: -mn ```word``` (Amrit Wilkhu)

### Objective :pushpin:
Let's say if someone has given a command as -mn<word>
- It will get the meaning of the word.

### Features to be added / modified :ballot_box_with_check:

- It gets the meaning of the word.

**Comment by KamalDGRT** [comment]
Closing this issue as @nanna7077 has completed it using Cogs.
