### ISSUE TITLE
[Bug] Small mistakes in Contribution_Guidelines.md

### ISSUE THREAD

**Issue by Manoj-Paramsetti** [DSC-SIST/Discord-Bot#49]
## 🐛 Bug Report

**Just a small issues in [Contribution_Guidelines.md](https://github.com/DSC-SIST/Discord-Bot/commit/1b03092676297d9c92516afeb111c9666102d83b#diff-2d390cfff25307bc497bb7d8475d524657491c50665fc480f25730b4335f573d)**
### Fenced code block is not closed properly
**In line 53:** The triple backtick is not given to close the fenced code block
**In line 60:** The triple backtick is not closed properly in the fenced code block

### Numbering of the points is incorrect
**In line 66:** Numbering of points is incorrect from line 66 (8 is repeated two times at line 56 and 66)

### Other issues
**In line 35:** Correct the spelling for the "relevant" word.
*Suggestion*
**In line 35:** Change the "PC" abbreviation word from lowercase to uppercase
#### Yes, I have read the contributing guidelines

**Comment by KamalDGRT** [comment]
Closing this issue as it is fixed!
